// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qcbmbehhpjecwwbdnsji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjYm1iZWhocGplY3d3YmRuc2ppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NzkwODUsImV4cCI6MjA2OTA1NTA4NX0.Cp8RRePZDJsBAkaD0b1InPL4i-ia65fOo2y-FrFhrik";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});